spring:
  application:
    name: twp-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      read:
        uri: ${SPRING_DATA_MONGODB_READ_URI}
#      chat:
#        uri: ${SPRING_DATA_MONGODB_CHAT_URI}

      auto-index-creation: true

    redis:
      host: localhost
      port: 6379

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

  jwt:
    secret: ${JWT_SECRET}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold: 10s
        permitted-number-of-calls-in-half-open-state: 3
        max-wait-duration-in-half-open-state: 0s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
    instances:
      circuit:
        base-config: default

feign:
  user:
    url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health           # 애플리케이션 상태 확인
          - prometheus       # 메트릭 데이터 노출

  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    with-credentials: true

logging:
  level:
    org.springframework.messaging: debug
    org.springframework.web.socket: debug

#websocket:
#  allowed-origin: "http://localhost:3000"
