spring:
  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 1
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: KAFKA_CONSUMER_GROUP_ID
      chat-group-id: KAFKA_CHAT_CONSUMER_GROUP_ID
      auto-offset-reset: earliest
      enable-auto-commit: false
    admin:
      properties:
        client.id: KAFKA_ADMIN_CLIENT_ID
    topics:
      chat-room: KAFKA_TOPIC_CHAT_ROOM
    partition-count: 1
    replication-factor: 1

thread-pool:
  noti:
    core-size: 20
    max-size: 100
    queue-capacity: 10

logging:
  level:
    org:
      springframework:
        data:
          redis:
            core: DEBUG
            connection: TRACE
          mongodb:
            core:
              MongoTemplate : DEBUG
            repository:
              query : DEBUG

    com:
      mongodb : DEBUG


websocket:
  allowed-origin: "http://localhost:3000"
